apiVersion: v1
kind: ConfigMap
metadata:
  name: timee-config
data:
  NODE_ENV: "production"
  PORT: "3001"
  CORS_ORIGIN: "https://wmxkwzbmhlj.sealoshzh.site"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timee-api
  labels:
    app: timee-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timee-api
  template:
    metadata:
      labels:
        app: timee-api
    spec:
      containers:
      - name: timee-api
        image: your-registry/timee-api:latest
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: timee-secrets
              key: database-url
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: timee-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: timee-config
              key: PORT
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: timee-config
              key: CORS_ORIGIN
        resources:
          requests:
            cpu: "0.1"
            memory: "128Mi"
          limits:
            cpu: "0.5"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: timee-api-service
spec:
  selector:
    app: timee-api
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP 