# 后端 API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timee-api
  namespace: timee-production
  labels:
    app: timee-api
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timee-api
  template:
    metadata:
      labels:
        app: timee-api
        component: backend
    spec:
      containers:
      - name: api
        image: your-registry/timee-api:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: API_PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: timee-secrets
              key: database-url
        - name: CORS_ORIGIN
          value: "https://timee.group"
        - name: ALLOWED_ORIGINS
          value: "https://timee.group,https://www.timee.group"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: timee-secrets
              key: jwt-secret
        - name: LOG_LEVEL
          value: "warn"
        - name: RATE_LIMIT_MAX
          value: "100"
        - name: RATE_LIMIT_WINDOW_MS
          value: "900000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
---
# 后端 API Service
apiVersion: v1
kind: Service
metadata:
  name: timee-api
  namespace: timee-production
  labels:
    app: timee-api
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: timee-api
---
# 数据库连接 Secret
apiVersion: v1
kind: Secret
metadata:
  name: timee-secrets
  namespace: timee-production
type: Opaque
data:
  # 注意：这些值需要 base64 编码
  # echo -n "postgresql://postgres:Qinguoqg123@timee-postgresql.ns-upg0e2qv.svc:5432/postgres" | base64
  database-url: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOlFpbmd1b3FnMTIzQHRpbWVlLXBvc3RncmVzcWwubnMtdXBnMGUycXYuc3ZjOjU0MzIvcG9zdGdyZXM="
  # echo -n "timee-super-secure-jwt-secret-2024" | base64
  jwt-secret: "dGltZWUtc3VwZXItc2VjdXJlLWp3dC1zZWNyZXQtMjAyNA==" 